hooks_enabled = true

[model]
temperature = 0

[[hooks]]
name='test_before_tool'
trigger='before_tool'
command='python3 ./scripts/test_tool.py'

[[hooks]]
name='test_before_agent'
trigger='before_agent'
command='python3 ./scripts/test_tool.py'

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "/Users/rivaanranawat/Desktop/ai-agent", "/tmp"]

[mcp_servers.filesystem2]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem222222222222", "/Users/rivaanranawat/Desktop/ai-agent", "/tmp"]

# Example custom model profiles:
#
# active_model_profile = "openai"
#
# [models.openai]
# base_url = "https://api.openai.com/v1"
# api_key_env = "OPENAI_API_KEY"
#
# [models.openai.model]
# name = "gpt-5-mini"
# temperature = 0.2
#
# [models.openrouter]
# base_url = "https://openrouter.ai/api/v1"
# api_key_env = "OPENROUTER_API_KEY"
#
# [models.openrouter.model]
# name = "nvidia/nemotron-3-super-120b-a12b:free"
# temperature = 0
